### ISSUE TITLE
When submitting a new server

### ISSUE THREAD

**Issue by OmniSyzygy** [Recouse/IPS-Server-Monitoring#1]
Monitoring\Exception\InvalidPacketException: Failed to read any data from socket (2)
#0 /home/theree9/public_html/forums/applications/monitoring/sources/Monitoring/Socket.php(76): Monitoring\BaseSocket->ReadInternal(Object(Monitoring\Buffer), 1400, Array)
#1 /home/theree9/public_html/forums/applications/monitoring/sources/Monitoring/SourceQuery.php(210): Monitoring\Socket->Read()
#2 /home/theree9/public_html/forums/applications/monitoring/sources/Server/GetInfo.php(50): Monitoring\SourceQuery->GetInfo()
#3 /home/theree9/public_html/forums/applications/monitoring/tasks/monitoringUpdate.php(80): IPS\monitoring\GetInfo->server(Array)
#4 /home/theree9/public_html/forums/system/Task/Task.php(172): IPS\monitoring\tasks_monitoringUpdate->execute()
#5 /home/theree9/public_html/forums/applications/monitoring/modules/admin/monitoring/server.php(213): IPS_Task->run()
#6 [internal function]: IPS\monitoring\modules\admin\monitoring_server->add()
#7 /home/theree9/public_html/forums/system/Dispatcher/Controller.php(85): call_user_func(Array)
#8 /home/theree9/public_html/forums/applications/monitoring/modules/admin/monitoring/server.php(54): IPS\Dispatcher_Controller->execute()
#9 /home/theree9/public_html/forums/system/Dispatcher/Dispatcher.php(129): IPS\monitoring\modules\admin\monitoring_server->execute()
#10 /home/theree9/public_html/forums/admin/index.php(13): IPS_Dispatcher->run()
#11 {main}

**Comment by OmniSyzygy** [comment]
A few details about above ^
It applied the server just fine, but says the Moderator is "Guest" even though I added a name. Might be related to that.

**Comment by Recouse** [comment]
Did you try to edit moderator in server's edit page?

**Comment by OmniSyzygy** [comment]
Yes, Though I don't know if that was the exact issue, as I added another server and got the same error without moderator.

**Comment by Recouse** [comment]
What game you adding?

**Comment by OmniSyzygy** [comment]
Garrysmod.

**Comment by Recouse** [comment]
I tested garrysmod on my site, all works.

**Comment by OmniSyzygy** [comment]
It might just be that same issue with missing dependencies. Though how would I check if I have all that? (As I'm sure I have php and allowing UDP Connections)

**Comment by Recouse** [comment]
Did you try to add other games?

**Comment by Recouse** [comment]
Closed. No response.
