### ISSUE TITLE
Overview Error

### ISSUE THREAD

**Issue by OmniSyzygy** [Recouse/IPS-Server-Monitoring#2]
Monitoring\Exception\InvalidPacketException: Failed to read any data from socket (2)
#0 /home/theree9/public_html/forums/applications/monitoring/sources/Monitoring/Socket.php(76): Monitoring\BaseSocket->ReadInternal(Object(Monitoring\Buffer), 1400, Array)
#1 /home/theree9/public_html/forums/applications/monitoring/sources/Monitoring/SourceQuery.php(210): Monitoring\Socket->Read()
#2 /home/theree9/public_html/forums/applications/monitoring/sources/Server/GetInfo.php(50): Monitoring\SourceQuery->GetInfo()
#3 /home/theree9/public_html/forums/applications/monitoring/tasks/monitoringUpdate.php(80): IPS\monitoring\GetInfo->server(Array)
#4 /home/theree9/public_html/forums/system/Task/Task.php(172): IPS\monitoring\tasks_monitoringUpdate->execute()
#5 /home/theree9/public_html/forums/applications/monitoring/modules/admin/monitoring/main.php(42): IPS_Task->run()
#6 /home/theree9/public_html/forums/system/Dispatcher/Controller.php(96): IPS\monitoring\modules\admin\monitoring_main->manage()
#7 /home/theree9/public_html/forums/applications/monitoring/modules/admin/monitoring/main.php(26): IPS\Dispatcher_Controller->execute()
#8 /home/theree9/public_html/forums/system/Dispatcher/Dispatcher.php(129): IPS\monitoring\modules\admin\monitoring_main->execute()
#9 /home/theree9/public_html/forums/admin/index.php(13): IPS_Dispatcher->run()
#10 {main}

**Comment by Recouse** [comment]
`Failed to read any data from socket` - it server problem, not application.

**Comment by Recouse** [comment]
Server requirements for good work:
-Modern PHP version (5.5 or newer)
-64-bit PHP or gmp module
-Web server must allow UDP connections
